/** @format */

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import N from "./navbar/page";
import Footer from "./footer/page";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
				// Ensure no dynamic or extension-injected attributes are present
				suppressHydrationWarning={true}>
				<N />
				<div className="flex-grow">{children}</div>
			</body>
		</html>
	);
}
