/** @format */
import React from "react";
export const metadata = {
	title: "Home Page",
	description: "Generated by create next app",
};
export default function Home() {
	return (
		<div>
			<h1 className="text-3xl font-bold ">Task Day 1</h1>
		</div>
	);
}
